# Stubs for toolz (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .itertoolz import *
from .functoolz import *
from .dicttoolz import *
from .recipes import *
from .compatibility import filter, map

sorted = sorted
comp = compose
