# Stubs for ete3 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .ncbi_taxonomy import *
from .coretype.tree import *
from .coretype.seqgroup import *
from .phylo.phylotree import *
from .evol.evoltree import *
from .webplugin.webapp import *
from .coretype.arraytable import *
from .clustering.clustertree import *
from .phylomedb.phylomeDB3 import *
from .treeview.svg_colors import *
from .treeview.main import *
from .treeview.faces import *
from .evol import EvolTree
from .nexml import Nexml, NexmlTree
from .phyloxml import Phyloxml, PhyloxmlTree
from .treeview import faces, layouts
from .version import __version__
