# Stubs for plumbum (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from types import ModuleType
from typing import Any, List

class LocalModule(ModuleType):
    __package__: Any = ...
    def __getattr__(self, name: Any): ...
    __path__: List[str] = ...
    __file__: Any = ...

cmd: Any
